###################
# BUILD FOR LOCAL DEVELOPMENT
###################
FROM node:21-alpine 

# Create app directory
WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

COPY --chown=node:node . .

RUN npm install && npm install -g dotenv-cli && npm install -g prisma

RUN npm install 

ENV NODE_ENV development

RUN ["chmod", "+x", "entrypoint-dev.sh"]

CMD ["entrypoint-dev.sh"]