version: '3.8'

services:

    web:
      container_name: nest-starter-app
      image: nest-starter
      # build:
      #   context: .
      #   target: development
      #   dockerfile: ./Dockerfile.dev
      ports:
        - 3000:3000
      env_file:
        - .env.development.local
      restart: unless-stopped
      entrypoint: /usr/src/app/entrypoint-dev.sh
      depends_on:
        - db
      networks:
        - nesjs-network
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes: 
        - mysql-volume:/var/lib/mysql:rw
      ports: 
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - nesjs-network

# networks:
#     nesjs-network:

volumes:
  mysql-volume:

networks:
  nesjs-network: